"""Module 4 — KL divergence and Bregman geometry of exponential families.

For two members p = p(. | eta_p), q = p(. | eta_q) of the same family,

    KL(p || q) = A(eta_q) - A(eta_p) - (eta_q - eta_p) . grad A(eta_p),

the Bregman divergence generated by the log-partition A. The mean parameters
mu = grad A(eta) are the dual coordinates; the convex conjugate A*(mu) is the negative
entropy; and the Fisher matrix F = Hessian A links the two coordinate systems. These
identities power CAVI (Module 6), natural-gradient SVI (Module 8) and the conjugate
updates of Module 5.
"""
from __future__ import annotations

from typing import Callable

import jax
import jax.numpy as jnp
from jax import lax
from jax.scipy.special import digamma, gammaln

from .m03_expfam import ExpFam

Array = jax.Array


# --------------------------------------------------------------------------------------
# Step 1: KL as a Bregman divergence, and a Monte Carlo reference
# --------------------------------------------------------------------------------------
def kl(fam: ExpFam, eta_p: Array, eta_q: Array) -> Array:
    """Closed-form KL(p_eta_p || p_eta_q) via the Bregman identity. Uses fam.log_partition
    and fam.mean_params only; no family-specific code."""
    # [m04 step 1]
    return fam.log_partition(eta_q) - fam.log_partition(eta_p) - jnp.dot(eta_q - eta_p, fam.mean_params(eta_p))


def kl_monte_carlo(fam: ExpFam, eta_p: Array, eta_q: Array, key: Array, n: int) -> tuple[Array, Array]:
    """Monte Carlo estimate of KL(p || q) = E_p[log p(x) - log q(x)] with n samples.

    Returns (estimate, standard_error)."""
    # [m04 step 1]
    xs = fam.sample(key, eta_p, n)
    lp = jax.vmap(fam.log_prob, in_axes=(0, None))
    diff = lp(xs, eta_p) - lp(xs, eta_q)
    return diff.mean(), diff.std() / jnp.sqrt(n)


# --------------------------------------------------------------------------------------
# Step 2: textbook closed forms, to be matched against the Bregman form
# --------------------------------------------------------------------------------------
def kl_bernoulli(p: Array, q: Array) -> Array:
    """KL(Bern(p) || Bern(q))."""
    # [m04 step 2]
    return p * (jnp.log(p) - jnp.log(q)) + (1 - p) * (jnp.log1p(-p) - jnp.log1p(-q))


def kl_categorical(p: Array, q: Array) -> Array:
    """KL between two length-K probability vectors."""
    # [m04 step 2]
    return jnp.sum(p * (jnp.log(p) - jnp.log(q)))


def kl_gamma(alpha_p: Array, beta_p: Array, alpha_q: Array, beta_q: Array) -> Array:
    """KL(Gamma(alpha_p, beta_p) || Gamma(alpha_q, beta_q)), shape/rate parameterisation."""
    # [m04 step 2]
    return (
        (alpha_p - alpha_q) * digamma(alpha_p)
        - gammaln(alpha_p)
        + gammaln(alpha_q)
        + alpha_q * (jnp.log(beta_p) - jnp.log(beta_q))
        + alpha_p * (beta_q - beta_p) / beta_p
    )


def kl_dirichlet(alpha_p: Array, alpha_q: Array) -> Array:
    """KL(Dir(alpha_p) || Dir(alpha_q))."""
    # [m04 step 2]
    a0p, a0q = alpha_p.sum(), alpha_q.sum()
    return (
        gammaln(a0p)
        - jnp.sum(gammaln(alpha_p))
        - gammaln(a0q)
        + jnp.sum(gammaln(alpha_q))
        + jnp.sum((alpha_p - alpha_q) * (digamma(alpha_p) - digamma(a0p)))
    )


# --------------------------------------------------------------------------------------
# Step 3: duality  mu <-> eta  and the convex conjugate
# --------------------------------------------------------------------------------------
def natural_from_mean(fam: ExpFam, mu: Array, eta0: Array, n_iter: int = 30) -> Array:
    """Invert mu = grad A(eta) for eta.

    Minimise the strictly convex objective f(eta) = A(eta) - eta . mu by damped Newton:
    direction d = -F(eta)^{-1} (grad A(eta) - mu), then the largest step in
    {1, 1/2, 1/4, ..., 2^-10} that keeps f finite and does not increase it (a plain
    Newton step can leave the natural-parameter domain, e.g. push a Gamma rate through
    zero, producing NaN). Run exactly n_iter iterations in lax.fori_loop and use only
    jnp.where for the step choice, so the result stays differentiable in mu.
    """
    # [m04 step 3]
    steps = 0.5 ** jnp.arange(11)

    def objective(eta):
        return fam.log_partition(eta) - jnp.dot(eta, mu)

    def step(_, eta):
        f0 = objective(eta)
        d = -jnp.linalg.solve(fam.fisher(eta), fam.mean_params(eta) - mu)
        cands = eta[None, :] + steps[:, None] * d[None, :]
        fc = jax.vmap(objective)(cands)
        ok = jnp.isfinite(fc) & (fc <= f0)
        idx = jnp.argmax(ok)  # first acceptable step (largest)
        any_ok = jnp.any(ok)
        return jnp.where(any_ok, cands[idx], eta)

    return lax.fori_loop(0, n_iter, step, eta0)


def conjugate(fam: ExpFam, mu: Array, eta0: Array, n_iter: int = 30) -> Array:
    """Convex conjugate A*(mu) = sup_eta [ eta . mu - A(eta) ] = eta(mu) . mu - A(eta(mu)).

    For families with log h = 0 this is the negative entropy of p_eta(mu)."""
    # [m04 step 3]
    eta = natural_from_mean(fam, mu, eta0, n_iter)
    return jnp.dot(eta, mu) - fam.log_partition(eta)


def entropy_monte_carlo(fam: ExpFam, eta: Array, key: Array, n: int) -> tuple[Array, Array]:
    """MC estimate of H(p_eta) = -E[log p(x)]. Returns (estimate, standard_error)."""
    # [m04 step 3]
    xs = fam.sample(key, eta, n)
    lp = jax.vmap(fam.log_prob, in_axes=(0, None))(xs, eta)
    return -lp.mean(), lp.std() / jnp.sqrt(n)


# --------------------------------------------------------------------------------------
# Step 4: the Fisher metric and natural gradients
# --------------------------------------------------------------------------------------
def natural_gradient(fam: ExpFam, eta: Array, grad_eta: Array) -> Array:
    """F(eta)^{-1} grad_eta: the natural gradient of a function whose ordinary gradient
    with respect to eta is grad_eta."""
    # [m04 step 4]
    return jnp.linalg.solve(fam.fisher(eta), grad_eta)


def kl_quadratic_approx(fam: ExpFam, eta: Array, delta: Array) -> Array:
    """Second-order approximation KL(p_eta || p_{eta+delta}) ~= 1/2 delta^T F(eta) delta."""
    # [m04 step 4]
    return 0.5 * delta @ fam.fisher(eta) @ delta
