"""Module 4 — KL divergence and Bregman geometry of exponential families.

For two members p = p(. | eta_p), q = p(. | eta_q) of the same family,

    KL(p || q) = A(eta_q) - A(eta_p) - (eta_q - eta_p) . grad A(eta_p),

the Bregman divergence generated by the log-partition A. The mean parameters
mu = grad A(eta) are the dual coordinates; the convex conjugate A*(mu) is the negative
entropy; and the Fisher matrix F = Hessian A links the two coordinate systems. These
identities power CAVI (Module 6), natural-gradient SVI (Module 8) and the conjugate
updates of Module 5.
"""
from __future__ import annotations

from typing import Callable

import jax
import jax.numpy as jnp
from jax import lax
from jax.scipy.special import digamma, gammaln

from .m03_expfam import ExpFam

Array = jax.Array


# --------------------------------------------------------------------------------------
# Step 1: KL as a Bregman divergence, and a Monte Carlo reference
# --------------------------------------------------------------------------------------
def kl(fam: ExpFam, eta_p: Array, eta_q: Array) -> Array:
    """Closed-form KL(p_eta_p || p_eta_q) via the Bregman identity. Uses fam.log_partition
    and fam.mean_params only; no family-specific code."""
    raise NotImplementedError  # Module 4, Step 1


def kl_monte_carlo(fam: ExpFam, eta_p: Array, eta_q: Array, key: Array, n: int) -> tuple[Array, Array]:
    """Monte Carlo estimate of KL(p || q) = E_p[log p(x) - log q(x)] with n samples.

    Returns (estimate, standard_error)."""
    raise NotImplementedError  # Module 4, Step 1


# --------------------------------------------------------------------------------------
# Step 2: textbook closed forms, to be matched against the Bregman form
# --------------------------------------------------------------------------------------
def kl_bernoulli(p: Array, q: Array) -> Array:
    """KL(Bern(p) || Bern(q))."""
    raise NotImplementedError  # Module 4, Step 2


def kl_categorical(p: Array, q: Array) -> Array:
    """KL between two length-K probability vectors."""
    raise NotImplementedError  # Module 4, Step 2


def kl_gamma(alpha_p: Array, beta_p: Array, alpha_q: Array, beta_q: Array) -> Array:
    """KL(Gamma(alpha_p, beta_p) || Gamma(alpha_q, beta_q)), shape/rate parameterisation."""
    raise NotImplementedError  # Module 4, Step 2


def kl_dirichlet(alpha_p: Array, alpha_q: Array) -> Array:
    """KL(Dir(alpha_p) || Dir(alpha_q))."""
    raise NotImplementedError  # Module 4, Step 2


# --------------------------------------------------------------------------------------
# Step 3: duality  mu <-> eta  and the convex conjugate
# --------------------------------------------------------------------------------------
def natural_from_mean(fam: ExpFam, mu: Array, eta0: Array, n_iter: int = 30) -> Array:
    """Invert mu = grad A(eta) for eta.

    Minimise the strictly convex objective f(eta) = A(eta) - eta . mu by damped Newton:
    direction d = -F(eta)^{-1} (grad A(eta) - mu), then the largest step in
    {1, 1/2, 1/4, ..., 2^-10} that keeps f finite and does not increase it (a plain
    Newton step can leave the natural-parameter domain, e.g. push a Gamma rate through
    zero, producing NaN). Run exactly n_iter iterations in lax.fori_loop and use only
    jnp.where for the step choice, so the result stays differentiable in mu.
    """
    raise NotImplementedError  # Module 4, Step 3


def conjugate(fam: ExpFam, mu: Array, eta0: Array, n_iter: int = 30) -> Array:
    """Convex conjugate A*(mu) = sup_eta [ eta . mu - A(eta) ] = eta(mu) . mu - A(eta(mu)).

    For families with log h = 0 this is the negative entropy of p_eta(mu)."""
    raise NotImplementedError  # Module 4, Step 3


def entropy_monte_carlo(fam: ExpFam, eta: Array, key: Array, n: int) -> tuple[Array, Array]:
    """MC estimate of H(p_eta) = -E[log p(x)]. Returns (estimate, standard_error)."""
    raise NotImplementedError  # Module 4, Step 3


# --------------------------------------------------------------------------------------
# Step 4: the Fisher metric and natural gradients
# --------------------------------------------------------------------------------------
def natural_gradient(fam: ExpFam, eta: Array, grad_eta: Array) -> Array:
    """F(eta)^{-1} grad_eta: the natural gradient of a function whose ordinary gradient
    with respect to eta is grad_eta."""
    raise NotImplementedError  # Module 4, Step 4


def kl_quadratic_approx(fam: ExpFam, eta: Array, delta: Array) -> Array:
    """Second-order approximation KL(p_eta || p_{eta+delta}) ~= 1/2 delta^T F(eta) delta."""
    raise NotImplementedError  # Module 4, Step 4
